name: LunarFreeCam
author: magas8
main: lunarfreecam.freecam.Main
description: A simple freecam plugin for all type of servers
version: ${project.version}
commands:
  freecam:
    usage: /freecam
    description: Used to set the player on freecam.
  roam:
    usage: /roam
    description: Used to set the player on freecam.