freecam-mode-on-success: '&8&l[&2&l!&8&l] &7Successfully went into FreeCam mode.'
freecam-mode-off-success: '&8&l[&2&l!&8&l] &7Successfully went back to your previous location.'
too-many-arguments-message: '&8&l[&c&l!&8&l] &7Too many arguments. Usage: &5/freecam'
cannot-use-commands-message: '&8&l[&c&l!&8&l] &7You cant use commands while in FreeCam mode.'
maximum-distance-reached-message: '&8&l[&c&l!&8&l] &7You have reached the maximum allowed distance.'
no-permission-message: '&8&l[&c&l!&8&l] &7You dont have permission to use this command.'
dummy:
  freecam-enabled: true
  disconnected: false
  kicked: false